# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2780f2484480dddda974db898da366c7fd2ba189475d25d7b2f5fe0f3b361cb6aca7414f7b98eed9f7eb029d988909c65c1d44cef12d0fc02bd6f2821a9fefd2

test:
  secret_key_base: 06918d7ae34f41a89d85f7e4bba99ce5c6dcaf3cdd434480e2aad20e553179b73ecd237a4f3088d79542b7de337f84da64dd4bdd03b09522faa322330dd51c14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
